"""The cacheable phrase library: every complete, fixed, reusable utterance
in the agent's vocabulary, organized by when it gets used.

Why *phrases*, not words: TTS caching only helps naturalness-neutral when
the cached unit is something a person would actually say as one breath.
Gluing together separately-synthesized individual words has no natural
coarticulation or sentence-level prosody across the joins - it's the
"robocall from 2005" sound, and it would work directly against the whole
point of this project (sounding human). A word-frequency list (the usual
meaning of "top 500 words") is built for text/reading-level analysis, not
for concatenative speech - there's no publicly meaningful "top 500 phrases"
corpus for a customer-service phone agent either, so these are hand-written
the same way the original backchannel pool was: real, complete phrases a
person would actually say in this context, not a frequency list.

Confirmed live and worth stating plainly: padding this file with phrases
just to hit a round number would cost real money for zero benefit. Every
phrase warmed here is a real TTS call, billed per character
(tts_fallback.py / the cost breakdown given in chat). A phrase that's in
the pool but has no real chance of being selected - or worse, that nothing
in the pipeline ever triggers at all - is money spent on audio nobody
hears. That's not hypothetical: it's exactly what was happening with HOLD
before this pass (see below), confirmed and fixed in this revision.

Three categories now, not four - GREETING, ACK (which now *includes* what
used to be a separate, unwired HOLD category), and CLOSING:

- greeting: the opening line. Previously generated by the LLM on every
  call (confirmed live: costs a full LLM+TTS round trip - the caller hears
  nothing for 1-2s+ at the very start of every single call, before they've
  said anything at all). Cached, it's instant - see run_local.py.
- ack: everything backchannel.py's choose_backchannel() can actually pick
  when a turn ends - short acknowledgments ("yeah,", "got it,") *and* the
  phrases that used to live in a separate HOLD category ("let me check
  that for you"). Merging them was a real fix, not just a rename: HOLD
  was cached (real money spent synthesizing it) but nothing in the
  pipeline ever selected it - confirmed live, 100% wasted spend. Folding
  it into the same pool choose_backchannel() already draws from means
  every phrase warmed here now has a real, working trigger, and the
  larger combined pool is a genuine naturalness win too - less repetition
  across a longer call. Also includes a handful of hybrid phrases that
  chain a short ack straight into a stall in one breath ("mm, got it, let
  me check that for you") - the way people actually talk, not strictly
  one or the other.
- closing: sign-off lines for a future "wrap up the call" flow that
  doesn't exist yet - no call-end detection is implemented anywhere in
  this pipeline. Deliberately *not* included in default warming
  (priority_phrases / what pipeline.py actually calls) for exactly the
  reason ack+hold got merged above: warming phrases nothing can trigger
  is real, avoidable cost for zero benefit. Written and kept here so
  wiring a real closing flow later is a one-line change, not a rewrite -
  but not warmed, not claimed as active, and excluded from the cost
  estimate accordingly.
"""

GREETING = {
    "en": [
        "Hi there, thanks for calling! How can I help you today?",
        "Hey! Thanks for reaching out, what can I do for you?",
        "Hello, thanks for calling in. What's going on?",
        "Hi, how can I help you today?",
        "Hey there, thanks for calling. What can I help with?",
    ],
    "hi": [
        "नमस्ते, कॉल करने के लिए धन्यवाद। मैं आपकी कैसे मदद कर सकता हूँ?",
        "नमस्ते, बताइए मैं आपकी क्या सहायता कर सकता हूँ?",
        "हैलो, आपका स्वागत है। मैं कैसे मदद करूँ?",
        "नमस्ते, कैसे मदद कर सकता हूँ आपकी?",
    ],
    "hinglish": [
        "Hey, thanks for calling! Kaise help kar sakta hoon?",
        "Namaste, bataiye kya help chahiye aapko?",
        "Hi, kaise madad kar sakta hoon aapki?",
        "Hey there, kaise help kar sakta hoon?",
    ],
}

# Short acknowledgments (the original backchannel pool) plus what used to
# be a separate, unwired HOLD category - both are things a person
# genuinely says right after someone finishes talking, while still
# thinking, so they share the same real selection mechanism
# (choose_backchannel in backchannel.py) instead of one of them sitting in
# the cache unused. Expanded for real variety since this is the one
# category with actual recurring usage across a call - more real,
# distinct entries here directly reduces repetition, unlike padding a
# category nothing selects from.
ACK = {
    "en": [
        # short acknowledgments
        "Mm-hmm,", "Right,", "Got it,", "Yeah,", "Okay,", "I see,", "Sure,", "Gotcha,",
        "Makes sense,", "Understood,", "Alright,", "Noted,", "For sure,", "Okay yeah,",
        # thinking/stalling (formerly the separate HOLD category)
        "Let me check that for you.", "One moment, please.", "Give me just a second.",
        "Let me pull that up.", "Hang on, I'm looking into it.",
        "Just a moment while I check that.", "Let me take a look.",
        "One sec, pulling that up now.", "Okay, let me see here.",
        # hybrid - a short ack chained into a stall in one breath, the way
        # people actually talk ("mm, got it, let me check that for you") -
        # requested explicitly after a live run happened to only sample the
        # plain short acks and plain stalls in one 5-turn call, never a
        # phrase combining both even though both exist in the pool.
        "Mm, got it, let me check that for you.",
        "Okay, gotcha - one sec, pulling that up.",
        "Right, let me take a look for you.",
        "Yeah, hang on, I'm looking into it.",
    ],
    "hi": [
        "हाँ,", "ठीक है,", "अच्छा,", "समझ गया,", "जी,", "बिल्कुल,", "ठीक,", "समझी बात,",
        "एक मिनट रुकिए, मैं देखता हूँ।", "ज़रा रुकिए, मैं चेक करता हूँ।",
        "बस एक सेकंड दीजिए।", "मैं अभी देखता हूँ, एक पल रुकिए।", "ठीक है, देखते हैं।",
        # hybrid - same short-ack-plus-stall combination as English above.
        "हाँ, समझ गया, एक मिनट रुकिए, मैं देखता हूँ।",
        "ठीक है, ज़रा रुकिए, मैं चेक करता हूँ।",
    ],
    "hinglish": [
        "Haan,", "Theek hai,", "Acha,", "Samajh gaya,", "Arre haan,", "Bilkul,", "Sahi hai,",
        "Ek second, main check karta hoon.", "Ruko zara, dekhta hoon.",
        "Bas ek minute dijiye.", "Ek sec, main dekh leta hoon.", "Ek min, dekhta hoon.",
        # hybrid - same short-ack-plus-stall combination as English above.
        "Haan, samajh gaya, ek second main check karta hoon.",
        "Theek hai, ruko zara, dekhta hoon.",
    ],
}

# Not wired into the pipeline - no call-end flow exists. Deliberately
# excluded from priority_phrases()/default warming so it doesn't repeat
# the exact waste that HOLD had before this revision. Kept here, real and
# ready, for whenever a real "wrap up the call" trigger gets built.
CLOSING = {
    "en": [
        "Thanks for calling, have a great day!",
        "Glad I could help. Take care!",
        "You're all set. Have a good one!",
        "Thanks for your patience, goodbye!",
        "Take care, and don't hesitate to call back.",
    ],
    "hi": [
        "कॉल करने के लिए धन्यवाद, आपका दिन शुभ हो।",
        "मदद कर पाकर खुशी हुई, अलविदा।",
        "धन्यवाद, अपना ख्याल रखिए।",
        "शुक्रिया, फिर बात करते हैं।",
    ],
    "hinglish": [
        "Call karne ke liye thanks, have a great day!",
        "Madad kar ke khushi hui, take care!",
        "Thanks yaar, bye!",
        "Shukriya, phir baat karte hain!",
    ],
}


def priority_phrases(language: str) -> list[str]:
    """Everything with a real, working trigger in the pipeline right now:
    greeting (played at call start) and ack (selected by
    choose_backchannel throughout the call). This is what pipeline.py
    actually warms - CLOSING is deliberately not included; see the module
    docstring for why warming a phrase nothing can trigger is real,
    avoidable cost, not future-proofing.
    """
    return list(GREETING.get(language, GREETING["en"])) + list(ACK.get(language, ACK["en"]))


def all_cacheable_phrases(language: str) -> list[str]:
    """Every phrase in the library, including CLOSING - for auditing what
    exists, or for deliberately warming the not-yet-wired category anyway
    (e.g. testing it before building the trigger). Not what pipeline.py
    calls by default - see priority_phrases().
    """
    phrases = []
    for bank in (GREETING, ACK, CLOSING):
        phrases.extend(bank.get(language, bank["en"]))
    return phrases
